language: c

os:
    - windows

import:

compiler:
    - gcc
    - clang



install: choco install make
choco install cmake

before_script:  
    - mkdir -p build
    - cd build
    - cmake ..

script:
    - make
    - ctest
  
