language: c

os:
    - windows

import:

compiler:
    - gcc
    - clang

before_install: skip


install:
    - choco install make
    - choco install cmake
before_script:  
    - mkdir -p build
    - cd build
    - cmake ..

script:
    --build c:/rep/test/build --config Release --target all -- -j 18
    - ctest
  
