language: c

os:
    - windows

import:

compiler:
    - gcc
    - clang

before_install: skip


install: make get-deps

before_script:  
    - mkdir -p build
    - cd build
    - cmake .. 

script: 
    - ctest
    make

  
