language: c       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os:
    # будем прогонять CI и на Linux, и на Mac OS X...
    - windows

compiler:
    # ... и с помощью GCC, и Clang
    - gcc
    - clang

    install: skip

script:
    - cmake .
    - cmake --build . -- -j2
