language: c       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os:
    # будем прогонять CI и на Linux, и на Mac OS X...
    - windows

compiler:
    # ... и с помощью GCC, и Clang
    - gcc
    - clang
before_install: skip


install: skip

before_script: skip

script:
   - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make Multi_coverage
     - ctest
