language: c

os:
    - windows

import:

compiler:
    - gcc
    - clang

before_install: skip


install: skip

before_script:  
    - mkdir -p build
    - cd build
    - cmake .. 

script:
    - make Multi.c
    - ctest
  
