language: c

os:
    - linux

import:

compiler:
    - gcc
    - clang

before_install: skip


install: skip
 - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
before_script:  
    - mkdir -p build
    - cd build
    - cmake .. 

script:
    - make
    - ctest
    

  
