language: c       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os:
    # будем прогонять CI и на Linux, и на Mac OS X...
    - windows

compiler:
    # ... и с помощью GCC, и Clang
    - gcc
    - clang
before_install: skip


install: skip

before_script: skip

script:
    - mkdir build1
    - cd build1
    - cmake ../Multi.c
    - make
    - ctest
  
