language: c

os:
    - windows

compiler:
    - gcc
    - clang

before_install: skip


install: skip

before_script:  
    - mkdir -p build
    - cd build
    - cmake .. 

script: 
    - ctest
    -make
  
