language: c

os:
    - windows

import:

compiler:
    - gcc
    - clang

before_install: make get-deps


install: skip

before_script:  
    - mkdir -p build
    - cd build
    - cmake .. 

script: 
    - ctest
    - make

  
